export const creditTitles = {
  writerDirector: "Writer / Director",
  director: "Director",
  directorProducer: "Director / Producer",
  coDirectorProductionDesign: "Co-Director / Prod Design",
  producerProductionDesign: "Producer / Prod Design",
  executiveProducer: "Executive Producer",
  executiveProducerEditor: "Exec. Prod / Editor",
  producers: "Producers",
  coProducer: "Co-Producer",
  productionDesign: "Prod Design",
  productionCompanies: "Production Companies",
  directorOfPhotography: "Director of Photography",
  firstAssistantDirector: "1st AD",
  secondAssistantDirector: "2nd AD",
  firstAssistantCamera: "1st AC",
  secondAssistantCamera: "2nd AC",
  productionAssistant: "Prod Assistant",
  bCamera: "B-Cam",
  btsVideo: "BTS Video",
  steadicamOperator: "Steadicam Operator",
  colourist: "Colourist",
  saxophone: "Saxophone",
} as const;
